/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sebastian
 */
public class JF_View_Libro extends javax.swing.JFrame {

    /**
     * Creates new form JF_View_Libro
     */
    public JF_View_Libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_titulo1 = new javax.swing.JLabel();
        lbl_autor = new javax.swing.JLabel();
        lbl_titulo2 = new javax.swing.JLabel();
        lbl_editorial = new javax.swing.JLabel();
        btn_ebook = new javax.swing.JButton();
        btn_papel = new javax.swing.JButton();
        lbl_titulo3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_titulo4 = new javax.swing.JLabel();
        lbl_isbn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_titulo5 = new javax.swing.JLabel();
        lbl_año = new javax.swing.JLabel();
        lbl_titulo6 = new javax.swing.JLabel();
        lbl_idioma = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_titulo7 = new javax.swing.JLabel();
        lbl_isbn1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_titulo8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Harry Potter_La piedra filosofal.jpg"))); // NOI18N

        lbl_titulo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("TITULO");
        lbl_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_titulo1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo1.setText("Autor:");

        lbl_autor.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_autor.setText("AUTOR");

        lbl_titulo2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo2.setText("Editorial:");

        lbl_editorial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_editorial.setText("EDITORIAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_titulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_titulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_ebook.setBackground(new java.awt.Color(255, 255, 255));
        btn_ebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ebook.png"))); // NOI18N
        btn_ebook.setBorder(null);
        btn_ebook.setBorderPainted(false);
        btn_ebook.setContentAreaFilled(false);
        btn_ebook.setOpaque(false);

        btn_papel.setBackground(new java.awt.Color(255, 255, 255));
        btn_papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comprar.png"))); // NOI18N
        btn_papel.setBorder(null);
        btn_papel.setBorderPainted(false);
        btn_papel.setContentAreaFilled(false);
        btn_papel.setOpaque(false);

        lbl_titulo3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lbl_titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo3.setText("Información adicional");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        lbl_titulo4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo4.setText("ISBN");
        jPanel3.add(lbl_titulo4);
        lbl_titulo4.setBounds(50, 10, 25, 16);

        lbl_isbn.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_isbn.setText("ISBN");
        jPanel3.add(lbl_isbn);
        lbl_isbn.setBounds(50, 30, 50, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ISBN.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 10, 32, 32);

        lbl_titulo5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo5.setText("Año");
        jPanel3.add(lbl_titulo5);
        lbl_titulo5.setBounds(380, 10, 21, 16);

        lbl_año.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_año.setText("AÑO");
        jPanel3.add(lbl_año);
        lbl_año.setBounds(380, 30, 50, 16);

        lbl_titulo6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo6.setText("Idioma");
        jPanel3.add(lbl_titulo6);
        lbl_titulo6.setBounds(380, 70, 35, 16);

        lbl_idioma.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_idioma.setText("IDIOMA");
        jPanel3.add(lbl_idioma);
        lbl_idioma.setBounds(380, 90, 50, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/libro.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 32, 32);

        lbl_titulo7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo7.setText("Páginas");
        jPanel3.add(lbl_titulo7);
        lbl_titulo7.setBounds(50, 70, 39, 16);

        lbl_isbn1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_isbn1.setText("PAGINAS");
        jPanel3.add(lbl_isbn1);
        lbl_isbn1.setBounds(50, 90, 50, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(340, 10, 32, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/idioma.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(340, 70, 32, 32);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbl_titulo8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_titulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo8.setText("Sinopsis");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(lbl_titulo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btn_ebook, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btn_papel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_papel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ebook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addComponent(lbl_titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_View_Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_View_Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_View_Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_View_Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_View_Libro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ebook;
    private javax.swing.JButton btn_papel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_año;
    private javax.swing.JLabel lbl_editorial;
    private javax.swing.JLabel lbl_idioma;
    private javax.swing.JLabel lbl_isbn;
    private javax.swing.JLabel lbl_isbn1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo1;
    private javax.swing.JLabel lbl_titulo2;
    private javax.swing.JLabel lbl_titulo3;
    private javax.swing.JLabel lbl_titulo4;
    private javax.swing.JLabel lbl_titulo5;
    private javax.swing.JLabel lbl_titulo6;
    private javax.swing.JLabel lbl_titulo7;
    private javax.swing.JLabel lbl_titulo8;
    // End of variables declaration//GEN-END:variables
}
